apiVersion: 0.3.0
environments:
  minikube:
    destination:
      namespace: default
      server: https://192.168.39.134:8443
    k8sVersion: v1.10.0
    path: minikube
kind: ksonnet.io/app
name: cassandra
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
